### ISSUE TITLE
Bold and Italic text do not work ?

### ISSUE THREAD

**Issue by niluved** [saminsohag/flutter_packages#14]
Hi, i'm having fun with your very cool package but for some reason i can't get a bold text out of it.
Please have a look at the following simple stateless widget and tell me what's wrong in here.
Thanks a lot

import 'package:flutter/material.dart';
import 'package:tex_markdown/tex_markdown.dart';

const String boldAndItalicText = r'''
This is an example of **bold** and *italic* text.
''';

class SampleBoldPage extends StatelessWidget {
  const SampleBoldPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: TexMarkdown(boldAndItalicText),
      ),
    );
  }
}

<img width="128" alt="Immagine 2024-06-11 175639" src="https://github.com/saminsohag/flutter_packages/assets/77725198/ac1e02f6-1dfe-4338-b42d-9806bb96fa7e">

**Comment by saminsohag** [comment]
Hi.. Please use gpt_markdown insted of tex_markdown package. tex_markdown has some problems. You don't have to configure a lot. Every think is same. just add gpt_markdown to pubspack.yml file and import it into the file you want to use TexMarkdown.

**Comment by niluved** [comment]
yes now it works fine, thanks
