### ISSUE TITLE
Add textDirection parameter

### ISSUE THREAD

**Issue by masfour7** [saminsohag/flutter_packages#4]
This package is great, but we are specifically interested in using it with the text direction being RTL. In the normal Flutter Text widget, this option is available and it would be great to have it in TexMarkdown as well.

**Comment by saminsohag** [comment]
I have added text textDirection parameter and published this package in pub.dav today. You can check the latest update. I haven't work with text direction being RTL. So if there is anything I can improve you can guide me I will try to implement that into the next version.

**Comment by masfour7** [comment]
Thank you @saminsohag. Yes, it worked perfectly.
