### ISSUE TITLE
Add textScaler parameter

### ISSUE THREAD

**Issue by masfour7** [saminsohag/flutter_packages#5]
It would be great if you could add this parameter: "textScaler" (textScaleFactor previously)

**Comment by saminsohag** [comment]
I can add "textScaler" parameter but I it is possible to change the font size of the text individually. So I am thinking not to add "textScaler" parameter.

``` dart
child: Theme(
  data: Theme.of(context).copyWith(
    textTheme: const TextTheme(
      // For H1.
      headlineLarge: TextStyle(fontSize: 55),
      // For H2.
      headlineMedium: TextStyle(fontSize: 45),
      // For H3.
      headlineSmall: TextStyle(fontSize: 35),
      // For H4.
      titleLarge: TextStyle(fontSize: 25),
      // For H5.
      titleMedium: TextStyle(fontSize: 15),
      // For H6.
      titleSmall: TextStyle(fontSize: 10),
    ),
  ),
  child: TexMarkdown(
    _controller.text,
    textDirection: _direction,
    onLinkTab: (url, title) {
      log(title, name: "title");
      log(url, name: "url");
    },
    style: const TextStyle(
      // Regular text font size here.
      fontSize: 15,
    ),
  ),
),
```

This is how you can change the font size of each heading and body text.

## Is this helpful?

**Comment by masfour7** [comment]
Our problem was that on small devices the text was shown Very Big. We want to make the font size smaller for small devices. 

By the way, we would love to talk more about improving your package; can you share your email or send us an email to info@infinitix.tech?
