### ISSUE TITLE
Latex Textoverflow

### ISSUE THREAD

**Issue by ZainRaza78** [saminsohag/flutter_packages#8]
Please add a SingleChildScrollView on latex as it overflows. 
![Screenshot 2024-03-31 004903](https://github.com/saminsohag/flutter_packages/assets/96280909/016fe382-8a5b-4fb3-9280-4b5c3e0df0fc)

**Comment by saminsohag** [comment]
I think you are using gpt_markdown package. I have shown some example how to make latex scrollable in the example folder of the repo. You can check the example and copy past to achieve scrolling.
