### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by ZainRaza78** [saminsohag/flutter_packages#9]
links "  onLinkTab: (url, title) =>" does not return any link a links are not clickable.

**Comment by saminsohag** [comment]
By the way. If you are using tex_markdown package then It will link tap will not work. Use gpt_markdown  package. And also If you are using flutter version 3.13 then Link will not be clickable because there was some issue with flutter in 3.13. If you are using 3.13 please update your flutter version.

**Comment by ZainRaza78** [comment]
i am using gpt_markdown but only the links which have these  square brackets before link e.g "[Amazon](https://www.amazon.com)" are clickable but which only link but no square brackets e.g  "https://www.amazon.com" are not clickable

**Comment by ZainRaza78** [comment]
i am using gpt_markdown but only the links which have these  square brackets before are clickable but which only link but no 

[Amazon](https://www.amazon.com)

**Comment by saminsohag** [comment]
```dart
  data = data.replaceAllMapped(
      RegExp(
          r"(https:\/\/www\.|http:\/\/www\.|https:\/\/|http:\/\/)?[a-zA-Z0-9]{2,}(\.[a-zA-Z0-9]{2,})(\.[a-zA-Z0-9]{2,})?"),
      (match) => "[${match[0]}](${match[0]})");

```

Use this function to achieve that method before passing data to TexMarkdown. It will convert `https://domain.com` to `[https://domain.com](https://domain.com)`.

Currently I am not supporting normal links for a reason. But You can use this method to achieve this feature.

## I hove this will be helpful for you.

**Comment by ZainRaza78** [comment]
thanks. From where did you learn all of this?

**Comment by saminsohag** [comment]
I have learned by youtube videos and using the official documentation page. Mostly self learning.
